/**
 * An OpenRocket design Debrief MADE UP, and the claim that says so.
 *
 * **Why this is generated rather than served.** The only real `.ork` this project can reach is
 * OpenRocket's own shipped example, which is **GPL-3.0-or-later** as part of that source tree. This
 * repository is MIT and `MAINTAINING.md`'s clean-room invariant says to keep it that way, so
 * publishing that file from `public/samples/` would mix a copyleft artifact into an MIT repo and a
 * deployed static site — a licensing judgment that belongs to the owner rather than to a session.
 * It is a poor demonstration besides: it states five simulations, which is D9's picker rather than
 * the overlay, and its 50.59 m apogee is two orders off any flight sample here. Recorded under
 * *Decisions taken without the owner* in `ROADMAP.md`, with the question parked in `OWNER-NOTES.md`.
 *
 * **A made-up PREDICTION is not a made-up FLIGHT, and conflating them is a real defect rather than
 * a wording preference.** `lib/synthetic.ts`'s `SYNTHETIC_NOTE` says *this flight* was invented, and
 * `isSynthetic` matches it exactly on `flight.notes`. `lib/ingest.ts` merges a design's
 * `PredictionContribution.notes` verbatim into the notes of the flight it pairs with — so putting
 * `SYNTHETIC_NOTE` on a design would make a REAL recording announce itself as invented on all two
 * dozen labelled sinks, the moment a flyer dropped this design beside their own log. That is a
 * worse breach than the unlabelled prediction it would be trying to prevent, and it is why the
 * claim below is its own sentence with its own constant.
 *
 * The distinction it has to carry: the flight is a measurement and the prediction is what missed
 * it. Here NEITHER was measured, and only the prediction's own note can say so once the design has
 * been paired with somebody else's flight.
 */

import type { SynthFlight } from './synthetic';

/**
 * The exact sentence the generated `.ork` carries inside it, in the design's own `<comment>`.
 *
 * Matched exactly rather than by keyword, for the reason `isSynthetic` records: the sentence is
 * always Debrief's own, so nobody weakens the claim by editing their copy, and nobody trips it by
 * writing the word "synthetic" into a design they really did fly.
 */
export const SYNTHETIC_DESIGN_MARKER =
  'DEBRIEF-SYNTHETIC-DESIGN: this design and its simulation were generated by Debrief as a demonstration.';

/**
 * The claim as it reaches a flyer, carried on the prediction's notes and therefore onto every
 * surface `lib/ingest.ts` merges those notes into.
 *
 * It says PREDICTION rather than flight, deliberately and in as many words, because the file it
 * rides on can be dropped beside a real recording — and in that pairing the flight IS a
 * measurement and only the prediction is invented.
 */
export const SYNTHETIC_DESIGN_NOTE =
  'This PREDICTION is SYNTHETIC — a design and a simulation Debrief made up to demonstrate the ' +
  'predicted-versus-flown comparison. No such rocket was designed and no simulator produced these ' +
  'figures, so no number in the Predicted column means anything about a real design. Where it is ' +
  'set beside a real recording, the recording is the measurement and this is not a prediction that ' +
  'missed it — it is not a prediction of it at all.';

/** Does this set of notes carry the made-up-design claim? Exact, for `isSynthetic`'s reason. */
export function isSyntheticDesign(notes: readonly string[] | undefined): boolean {
  return (notes ?? []).some((n) => n === SYNTHETIC_DESIGN_NOTE);
}

/** Read the marker out of a design's XML. Returns the NOTE Debrief will state, never the file's
 *  own words — the file only gets to say whether the claim applies, not how it is phrased. */
export function syntheticDesignFromXml(xml: string): string | null {
  return xml.includes(SYNTHETIC_DESIGN_MARKER) ? SYNTHETIC_DESIGN_NOTE : null;
}

/** CRC-32, computed the long way so this module depends on nothing. */
function crc32(data: Uint8Array): number {
  let crc = 0xffffffff;
  for (let i = 0; i < data.length; i++) {
    crc ^= data[i];
    for (let k = 0; k < 8; k++) crc = crc & 1 ? 0xedb88320 ^ (crc >>> 1) : crc >>> 1;
  }
  return (crc ^ 0xffffffff) >>> 0;
}

/**
 * A minimal STORED (uncompressed) ZIP holding one member, little-endian per PKWARE APPNOTE.
 *
 * **Stored rather than deflated, and that is a requirement rather than a shortcut.** The file this
 * writes is COMMITTED and `lib/samples.test.ts` compares it to its generator byte for byte, which
 * only works if the bytes are a pure function of the input. `lib/zip.ts` already writes archives —
 * and it is async, returns a `Blob`, and deflates through `CompressionStream`, whose output is not
 * guaranteed stable across zlib versions. A regeneration check built on that would drift for
 * reasons that have nothing to do with this repo. OpenRocket deflates its own files; the reader
 * takes method 0 as well, which is what makes the deterministic route available.
 *
 * No timestamps, for the same reason `lib/synthetic.ts` has no clock in it.
 */
export function storedZip(name: string, contents: string): Uint8Array {
  const data = new TextEncoder().encode(contents);
  const nameBuf = new TextEncoder().encode(name);
  const crc = crc32(data);

  const local = new Uint8Array(30);
  const lv = new DataView(local.buffer);
  lv.setUint32(0, 0x04034b50, true);
  lv.setUint16(4, 20, true);
  lv.setUint16(8, 0, true); // stored
  lv.setUint32(14, crc, true);
  lv.setUint32(18, data.length, true);
  lv.setUint32(22, data.length, true);
  lv.setUint16(26, nameBuf.length, true);

  const central = new Uint8Array(46);
  const cv = new DataView(central.buffer);
  cv.setUint32(0, 0x02014b50, true);
  cv.setUint16(4, 20, true);
  cv.setUint16(6, 20, true);
  cv.setUint16(10, 0, true);
  cv.setUint32(16, crc, true);
  cv.setUint32(20, data.length, true);
  cv.setUint32(24, data.length, true);
  cv.setUint16(28, nameBuf.length, true);
  cv.setUint32(42, 0, true); // local header offset

  const localSize = local.length + nameBuf.length + data.length;
  const centralSize = central.length + nameBuf.length;
  const eocd = new Uint8Array(22);
  const ev = new DataView(eocd.buffer);
  ev.setUint32(0, 0x06054b50, true);
  ev.setUint16(8, 1, true);
  ev.setUint16(10, 1, true);
  ev.setUint32(12, centralSize, true);
  ev.setUint32(16, localSize, true);

  const parts = [local, nameBuf, data, central, nameBuf, eocd];
  const total = parts.reduce((n, p) => n + p.length, 0);
  const out = new Uint8Array(total);
  let at = 0;
  for (const p of parts) {
    out.set(p, at);
    at += p.length;
  }
  return out;
}

/** The member name a `.ork` must hold, fixed by the format. */
export const DESIGN_MEMBER = 'rocket.ork';

/** Speed of sound the stated Mach is consistent with, in m/s. `lib/parsers/openrocket.ts` re-derives
 *  `maxvelocity / maxmach` on every file it opens and DROPS the run when the result falls outside
 *  280–380, so a generator that ignores this ships a design whose figures silently never appear. */
const SOUND_MS = 340.0;

/**
 * The prediction that pairs with `demoFlight()`, as a real `.ork` archive.
 *
 * **All ten figures are derived from the flight it pairs with, and none is typed in**, so the two
 * cannot drift apart when the generator's curve is edited — and so the "miss" is a stated,
 * single-place decision instead of ten numbers that happen to differ. `MISS` is what makes this
 * demonstrate anything: a prediction that matched the flight exactly would show a comparison with
 * nothing in it, and the one thing D9's cross-check exists to show is the gap.
 *
 * **This docstring claimed that before it was true, and the pre-push review found three constants
 * behind it.** `maxacceleration` was a hardcoded `108.2`, `deploymentvelocity` a hardcoded `2.6`,
 * and `optimumdelay` a hardcoded `2.8` — the last of which is physically absurd for this curve: an
 * optimum ejection delay is the coast from burnout to apogee, which is seventeen and a half
 * seconds here, so a 2.8 s delay fires the charge at about 140 m/s. A demonstration sample stating
 * a figure that a reader who knows the quantity would recognise as nonsense teaches the wrong
 * thing about the tool reading it.
 *
 * The direction is the honest one for the curve `demoFlight` draws. That curve ignores drag on the
 * way up and says so, so it flies HIGHER than a real motor of its impulse would — which means a
 * simulation of the same rocket, with drag in it, predicts LESS. The design under-predicts by 4%.
 *
 * None of that makes either number a claim about a real rocket. Both are invented, the archive
 * carries `SYNTHETIC_DESIGN_MARKER` saying so, and `lib/parsers/openrocket.ts` turns that into a
 * note that travels with the figures.
 */
export function demoDesign(flight: SynthFlight, rocketName = 'Demonstrator'): Uint8Array {
  const s = flight.samples;
  const alts = s.map((p) => p.altitude);
  const apogeeIdx = alts.indexOf(Math.max(...alts));
  const apogee = alts[apogeeIdx];
  const apogeeAt = s[apogeeIdx].t;
  const vMax = Math.max(...s.map((p) => p.velocity));
  const flightTime = s[s.length - 1].t;

  // **The LANDING speed is the last leg's, not the fastest descent.** A first cut took
  // `-Math.min(velocity)` and called it `landingSpeed`; on this curve that is the DROGUE rate
  // (7.5 m/s) and the rocket lands under main at 4.2 m/s. The report prints both legs on the same
  // screen as the predicted ground-hit figure, so the sample contradicted itself in public — and
  // the wrong variable name is what made it invisible. Read off the end of the record, which is
  // where a ground-hit velocity is by definition.
  const landing = -s[s.length - 2].velocity;

  // Rail exit: the speed the moment the rocket clears a 6 ft rail. Derived rather than guessed at
  // a fraction of the peak, which is what `vMax * 0.09` was.
  const RAIL_M = 1.83;
  const railIdx = s.findIndex((p) => p.altitude >= RAIL_M);
  const railExit = railIdx > 0 ? s[railIdx].velocity : 0;

  // Burnout is where the curve stops gaining speed; the optimum delay is the coast from there to
  // apogee, which is what the quantity MEANS. A typed-in 2.8 s fired the charge at about 140 m/s
  // on a flight that coasts for seventeen and a half seconds.
  const burnoutIdx = s.findIndex((p, i) => i > 0 && p.velocity < s[i - 1].velocity);
  const burnoutAt = burnoutIdx > 0 ? s[burnoutIdx - 1].t : 0;
  const optimumDelay = apogeeAt - burnoutAt;

  // Deployment: the speed a charge fired at apogee actually sees, taken a beat after the peak
  // rather than assumed to be zero.
  const deployIdx = Math.min(s.length - 1, apogeeIdx + 10);
  const deployment = Math.abs(s[deployIdx].velocity);

  // Peak acceleration off the curve itself, so it moves when the curve does.
  let peakAccel = 0;
  for (let i = 1; i < s.length; i++) {
    const dt = s[i].t - s[i - 1].t;
    if (dt <= 0) continue;
    peakAccel = Math.max(peakAccel, (s[i].velocity - s[i - 1].velocity) / dt);
  }

  /** How far the simulation sits under the flight. ONE number, so the miss is a decision rather
   *  than ten figures that happen to differ — and applied to all ten, because a simulation that
   *  matched the flight on some quantities and not others would be modelling something. */
  const MISS = 0.96;
  const r = (v: number, places: number) => {
    const f = 10 ** places;
    return String(Math.round(v * f) / f);
  };

  const maxvelocity = vMax * MISS;
  const sim =
    `<simulation status="uptodate"><name>Demonstration</name>` +
    `<flightdata maxaltitude="${r(apogee * MISS, 2)}" maxvelocity="${r(maxvelocity, 3)}" ` +
    `maxacceleration="${r(peakAccel * MISS, 3)}" maxmach="${r(maxvelocity / SOUND_MS, 4)}" ` +
    `timetoapogee="${r(apogeeAt * MISS, 2)}" flighttime="${r(flightTime * MISS, 2)}" ` +
    `groundhitvelocity="${r(landing * MISS, 3)}" launchrodvelocity="${r(railExit * MISS, 3)}" ` +
    `deploymentvelocity="${r(deployment * MISS, 3)}" optimumdelay="${r(optimumDelay * MISS, 3)}"/></simulation>`;

  const xml =
    `<?xml version='1.0' encoding='utf-8'?>` +
    `<openrocket version="1.10" creator="Debrief — synthesized demonstration, not OpenRocket">` +
    `<rocket><name>${rocketName}</name>` +
    `<comment>${SYNTHETIC_DESIGN_MARKER}</comment>` +
    `</rocket><simulations>${sim}</simulations></openrocket>`;

  return storedZip(DESIGN_MEMBER, xml);
}
