import { describe, it, expect } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { importFlight } from './index';
import { analyzeFlight } from '../analyze';
import { getChannel, type ChannelKind } from '../flight/types';
import { convert } from '../units';
import { decodeBytes } from '../encoding';

// Golden-value regression against the full private flight-log corpus (61 real logs across
// 10 logger families). The corpus is fetched on demand into ./__corpus__/ by
// `npm run fetch-fixtures` (needs FIXTURES_TOKEN). When it isn't present — a public clone,
// a fork's CI without the secret — this whole suite skips, so the public build stays green.
//
// The contract lives in __corpus__/expected.json, generated by running THIS pipeline over
// the corpus and pairing it with each file's ground truth (device summary / second altimeter).
// Each fixture asserts one of: an auto-detected parser + numeric headline numbers within a
// tolerance of ground truth; a generic-mapper fallback with the right roles; or a deliberate
// rejection (Blue Raven high-rate files). Files Debrief currently mis-reads are recorded with
// a `knownIssue` and parsed-but-not-asserted, so the corpus documents the gap without locking
// a wrong number in as correct — fix the parser, then drop the knownIssue to turn on the assert.

const CORPUS = fileURLToPath(new URL('./__corpus__/', import.meta.url));
const SPEC = `${CORPUS}expected.json`;
const present = existsSync(SPEC);

const G0 = 9.80665;

type Assert = { metric: string; value: number; unit: string; tolPct: number };
interface Fixture {
  file: string;
  expect: { kind: 'flight' | 'mapping' | 'reject'; parser?: string; rejectMatch?: string };
  requireChannels?: string[];
  requireRoles?: string[];
  assert?: Assert[];
  knownIssue?: string;
  note?: string;
}

/** Convert one of Debrief's SI metrics into the unit the ground truth is stated in. */
function toStatedUnit(metric: string, si: number, unit: string): number {
  if (metric === 'maxAccel' && (unit === 'g' || unit === 'G')) return si / G0;
  const from = metric === 'apogee' ? 'm' : metric === 'maxAccel' ? 'm/s²' : 'm/s';
  return convert(si, from, unit);
}
const metricSI: Record<string, (m: ReturnType<typeof analyzeFlight>['metrics']) => number | null> = {
  apogee: (m) => m.apogeeAltitude,
  maxVelocity: (m) => m.maxVelocity,
  maxAccel: (m) => m.maxAcceleration,
  drogue: (m) => m.drogueDescentRate,
  main: (m) => m.mainDescentRate,
};

function runFixture(fx: Fixture) {
  const name = fx.file.split('/').pop() as string;
  // Decode from the raw bytes exactly as the app does (a file's bytes → decodeBytes),
  // not as UTF-8 — otherwise a UTF-16 export (e.g. the RRC3 mDACS text file) would be
  // tested as mojibake the real drop-a-file path never sees. Keeps the corpus faithful
  // to production input.
  const text = decodeBytes(new Uint8Array(readFileSync(CORPUS + fx.file)));

  if (fx.expect.kind === 'reject') {
    // Debrief declines these on purpose (e.g. a Blue Raven high-rate file with no altitude)
    // with a helpful, user-facing message.
    expect(() => importFlight({ name, text })).toThrow(fx.expect.rejectMatch);
    return;
  }

  const res = importFlight({ name, text });
  expect(res.kind).toBe(fx.expect.kind);

  if (res.kind === 'mapping') {
    const roles = res.table.columns.map((c) => c.role);
    for (const r of fx.requireRoles ?? []) expect(roles, `role ${r}`).toContain(r);
    return;
  }
  if (res.kind !== 'flight') return;

  if (fx.expect.parser) expect(res.parser.id).toBe(fx.expect.parser);
  for (const ch of fx.requireChannels ?? []) {
    expect(getChannel(res.flight, ch as ChannelKind), `channel ${ch}`).toBeTruthy();
  }

  // A documented mis-read or intentional anomaly: prove it still parses without throwing,
  // but don't assert the (known-wrong / meaningless) numbers.
  if (fx.knownIssue) return;

  if (fx.assert?.length) {
    const a = analyzeFlight(res.flight);
    for (const as of fx.assert) {
      const si = metricSI[as.metric](a.metrics);
      expect(si, `${as.metric} present`).not.toBeNull();
      expect(Number.isNaN(si as number), `${as.metric} is NaN`).toBe(false);
      const got = toStatedUnit(as.metric, si as number, as.unit);
      const lo = as.value * (1 - as.tolPct / 100);
      const hi = as.value * (1 + as.tolPct / 100);
      expect(got, `${as.metric} ${got.toFixed(1)} ${as.unit} vs ${as.value}±${as.tolPct}%`).toBeGreaterThanOrEqual(lo);
      expect(got, `${as.metric} ${got.toFixed(1)} ${as.unit} vs ${as.value}±${as.tolPct}%`).toBeLessThanOrEqual(hi);
    }
  }
}

describe('private corpus regression (lib/parsers/__corpus__)', () => {
  if (!present) {
    it.skip('corpus not fetched — run `npm run fetch-fixtures` (needs FIXTURES_TOKEN)', () => {});
    return;
  }
  const spec = JSON.parse(readFileSync(SPEC, 'utf8')) as { fixtures: Fixture[] };
  for (const fx of spec.fixtures) {
    it(`${fx.file}${fx.knownIssue ? ' [known issue: parse-only]' : ''}`, () => runFixture(fx));
  }
});
