import { describe, it, expect } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { importFlight } from './index';
import { analyzeFlight } from '../analyze';
import { buildFlight } from '../flight/build';
import { compareReported } from '../flight/reported';
import { getChannel, type ChannelKind } from '../flight/types';
import { convert } from '../units';
import { decodeBytes } from '../encoding';

// Golden-value regression against the full private flight-log corpus (61 real logs across
// 10 logger families). The corpus is fetched on demand into ./__corpus__/ by
// `npm run fetch-fixtures` (needs FIXTURES_TOKEN). When it isn't present — a public clone,
// a fork's CI without the secret — this whole suite skips, so the public build stays green.
//
// The contract lives in __corpus__/expected.json, generated by running THIS pipeline over
// the corpus and pairing it with each file's ground truth (device summary / second altimeter).
// Each fixture asserts one of: an auto-detected parser + numeric headline numbers within a
// tolerance of ground truth; a generic-mapper fallback with the right roles; or a deliberate
// rejection (Blue Raven high-rate files). Files Debrief currently mis-reads are recorded with
// a `knownIssue` and parsed-but-not-asserted, so the corpus documents the gap without locking
// a wrong number in as correct — fix the parser, then drop the knownIssue to turn on the assert.

const CORPUS = fileURLToPath(new URL('./__corpus__/', import.meta.url));
const SPEC = `${CORPUS}expected.json`;
const present = existsSync(SPEC);

const G0 = 9.80665;

type Assert = { metric: string; value: number; unit: string; tolPct: number };
interface Fixture {
  file: string;
  expect: { kind: 'flight' | 'mapping' | 'reject'; parser?: string; rejectMatch?: string };
  requireChannels?: string[];
  requireRoles?: string[];
  assert?: Assert[];
  knownIssue?: string;
  note?: string;
}

/** Convert one of Debrief's SI metrics into the unit the ground truth is stated in. */
function toStatedUnit(metric: string, si: number, unit: string): number {
  if (metric === 'maxAccel' && (unit === 'g' || unit === 'G')) return si / G0;
  const from = metric === 'apogee' ? 'm' : metric === 'maxAccel' ? 'm/s²' : 'm/s';
  return convert(si, from, unit);
}
const metricSI: Record<string, (m: ReturnType<typeof analyzeFlight>['metrics']) => number | null> = {
  apogee: (m) => m.apogeeAltitude,
  maxVelocity: (m) => m.maxVelocity,
  maxAccel: (m) => m.maxAcceleration,
  drogue: (m) => m.drogueDescentRate,
  main: (m) => m.mainDescentRate,
};

/**
 * Physical/logical invariants every real flight's analysis must satisfy, whatever
 * the logger — a standing guard against a metric that contradicts itself (the kind
 * of bug that a golden-value assert on one number can miss). Checked on every
 * non-anomalous corpus flight, so a regression anywhere in the pipeline trips here.
 */
function assertInvariants(a: ReturnType<typeof analyzeFlight>, name: string): void {
  const m = a.metrics;
  const apo = m.apogeeAltitude;
  const ctx = (msg: string) => `${name}: ${msg}`;

  // Deceleration is a deceleration — never a positive number dressed up as one.
  if (Number.isFinite(m.maxDeceleration)) expect(m.maxDeceleration, ctx('maxDeceleration ≤ 0')).toBeLessThanOrEqual(0);
  // Max acceleration and boost average are positive, and the average never exceeds the peak.
  if (m.avgBoostAcceleration != null) {
    expect(m.avgBoostAcceleration, ctx('avgBoost > 0')).toBeGreaterThan(0);
    if (Number.isFinite(m.maxAcceleration)) expect(m.avgBoostAcceleration, ctx('avgBoost ≤ max')).toBeLessThanOrEqual(m.maxAcceleration + 0.5);
  }
  // Thrust-to-weight off the pad, when read, is a sane launch number.
  if (m.liftoffTWR != null) {
    expect(m.liftoffTWR, ctx('TWR ≥ 1')).toBeGreaterThanOrEqual(1);
    expect(m.liftoffTWR, ctx('TWR < 100')).toBeLessThan(100);
  }
  // The design points all happen at or below apogee.
  if (Number.isFinite(m.maxVelocity)) expect(m.maxVelocityAltitude, ctx('maxVelAlt ≤ apogee')).toBeLessThanOrEqual(apo + 5);
  if (m.maxDynamicPressureAltitude != null) expect(m.maxDynamicPressureAltitude, ctx('maxQ alt ≤ apogee')).toBeLessThanOrEqual(apo + 5);
  if (m.transonicAltitude != null) expect(m.transonicAltitude, ctx('transonic alt ≤ apogee')).toBeLessThanOrEqual(apo + 5);
  if (m.burnoutAltitude != null) expect(m.burnoutAltitude, ctx('burnout alt ≤ apogee')).toBeLessThanOrEqual(apo + 5);
  // Descent rates are downward (positive); the main is the slow chute.
  if (m.drogueDescentRate != null) expect(m.drogueDescentRate, ctx('drogue ≥ 0')).toBeGreaterThanOrEqual(0);
  if (m.mainDescentRate != null) expect(m.mainDescentRate, ctx('main ≥ 0')).toBeGreaterThanOrEqual(0);
  if (m.drogueDescentRate != null && m.mainDescentRate != null) expect(m.mainDescentRate, ctx('main ≤ drogue')).toBeLessThanOrEqual(m.drogueDescentRate + 0.5);
  // The clock adds up: boost + coast = time to apogee; ascent + descent = flight.
  if (m.burnTime != null && m.coastTime != null && Number.isFinite(m.timeToApogee))
    expect(Math.abs(m.burnTime + m.coastTime - m.timeToApogee), ctx('burn + coast = timeToApogee')).toBeLessThanOrEqual(Math.max(0.5, m.timeToApogee * 0.1));
  if (m.descentTime != null && m.flightTime != null && Number.isFinite(m.timeToApogee))
    expect(Math.abs(m.timeToApogee + m.descentTime - m.flightTime), ctx('ascent + descent = flight')).toBeLessThanOrEqual(0.5);
  // Battery only sags under load — the minimum never exceeds the resting start.
  if (m.batteryStartV != null && m.batteryMinV != null) expect(m.batteryMinV, ctx('battMin ≤ battStart')).toBeLessThanOrEqual(m.batteryStartV + 0.05);
  // Events are in flight order and none sits above apogee.
  const order = ['liftoff', 'burnout', 'apogee', 'main', 'landing']
    .map((t) => a.events.find((e) => e.type === t))
    .filter(Boolean) as { time: number; altitude: number; type: string }[];
  for (let i = 1; i < order.length; i++) expect(order[i].time, ctx(`${order[i - 1].type} before ${order[i].type}`)).toBeGreaterThanOrEqual(order[i - 1].time - 1e-6);
  for (const e of order) expect(e.altitude, ctx(`${e.type} not above apogee`)).toBeLessThanOrEqual(apo + 1);
}

function runFixture(fx: Fixture) {
  const name = fx.file.split('/').pop() as string;
  // Decode from the raw bytes exactly as the app does (a file's bytes → decodeBytes),
  // not as UTF-8 — otherwise a UTF-16 export (e.g. the RRC3 mDACS text file) would be
  // tested as mojibake the real drop-a-file path never sees. Keeps the corpus faithful
  // to production input.
  const text = decodeBytes(new Uint8Array(readFileSync(CORPUS + fx.file)));

  if (fx.expect.kind === 'reject') {
    // Debrief declines these on purpose (e.g. a Blue Raven high-rate file with no altitude)
    // with a helpful, user-facing message.
    expect(() => importFlight({ name, text })).toThrow(fx.expect.rejectMatch);
    return;
  }

  const res = importFlight({ name, text });
  expect(res.kind).toBe(fx.expect.kind);

  if (res.kind === 'mapping') {
    const t = res.table;
    const roles = t.columns.map((c) => c.role);
    for (const r of fx.requireRoles ?? []) expect(roles, `role ${r}`).toContain(r);
    // Exercise the full generic-mapper → build → analyze path on a real file. Mapping
    // fixtures were only role-checked, so a regression in analysing a mapped flight —
    // or in reconciling it against the device's own reported figures — was invisible.
    // Only when the auto-mapping found the essentials and the read isn't a known issue.
    const hasTime = roles.includes('time');
    const hasAltitude = roles.includes('altitude') || roles.includes('pressure');
    if (!fx.knownIssue && hasTime && hasAltitude) {
      const mappings = t.columns.filter((c) => c.role !== 'ignore').map((c) => ({ index: c.index, role: c.role, unit: c.unit }));
      const flight = buildFlight({
        source: name,
        format: 'generic',
        formatLabel: 'Generic CSV',
        headers: t.headers,
        dataRows: t.dataRows,
        mappings,
        reported: t.reported,
      });
      const a = analyzeFlight(flight);
      expect(Number.isFinite(a.metrics.apogeeAltitude), `${name} apogee finite`).toBe(true);
      expect(a.metrics.apogeeAltitude, `${name} apogee > 0`).toBeGreaterThan(0);
      assertInvariants(a, name);
      // Where the file states the device's own apogee, Debrief's independent read must
      // agree closely — a grounded guard that a real generic-CSV flight stays correct.
      for (const c of compareReported(flight.reported ?? [], a.metrics)) {
        if (c.reported.metric === 'apogeeAltitude' && c.hasComputed) {
          expect(c.deltaPct!, `${name} apogee ${convert(c.computed, 'm', 'ft').toFixed(0)}ft vs device ${convert(c.reported.value, 'm', 'ft').toFixed(0)}ft`).toBeLessThan(5);
        }
      }
    }
    return;
  }
  if (res.kind !== 'flight') return;

  if (fx.expect.parser) expect(res.parser.id).toBe(fx.expect.parser);
  for (const ch of fx.requireChannels ?? []) {
    expect(getChannel(res.flight, ch as ChannelKind), `channel ${ch}`).toBeTruthy();
  }

  // A documented mis-read or intentional anomaly: prove it still parses without throwing,
  // but don't assert the (known-wrong / meaningless) numbers or the invariants.
  if (fx.knownIssue) return;

  // Every real flight must satisfy the physical/logical invariants, whether or not
  // it carries golden-value asserts.
  const a = analyzeFlight(res.flight);
  assertInvariants(a, name);

  if (fx.assert?.length) {
    for (const as of fx.assert) {
      const si = metricSI[as.metric](a.metrics);
      expect(si, `${as.metric} present`).not.toBeNull();
      expect(Number.isNaN(si as number), `${as.metric} is NaN`).toBe(false);
      const got = toStatedUnit(as.metric, si as number, as.unit);
      const lo = as.value * (1 - as.tolPct / 100);
      const hi = as.value * (1 + as.tolPct / 100);
      expect(got, `${as.metric} ${got.toFixed(1)} ${as.unit} vs ${as.value}±${as.tolPct}%`).toBeGreaterThanOrEqual(lo);
      expect(got, `${as.metric} ${got.toFixed(1)} ${as.unit} vs ${as.value}±${as.tolPct}%`).toBeLessThanOrEqual(hi);
    }
  }
}

describe('private corpus regression (lib/parsers/__corpus__)', () => {
  if (!present) {
    it.skip('corpus not fetched — run `npm run fetch-fixtures` (needs FIXTURES_TOKEN)', () => {});
    return;
  }
  const spec = JSON.parse(readFileSync(SPEC, 'utf8')) as { fixtures: Fixture[] };
  for (const fx of spec.fixtures) {
    it(`${fx.file}${fx.knownIssue ? ' [known issue: parse-only]' : ''}`, () => runFixture(fx));
  }
});
