import { describe, it, expect } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { importFlight } from './index';
import { analyzeFlight } from '../analyze';
import { buildFlight } from '../flight/build';
import { compareReported } from '../flight/reported';
import { getChannel, type ChannelKind } from '../flight/types';
import { convert } from '../units';
import { decodeBytes } from '../encoding';
import { buildComparison, crossCheck, type CompareInput } from '../compare';
import { peakAgreement, peakTimeTolerance } from '../crossPeak';

// Golden-value regression against the full private flight-log corpus (61 real logs across
// 10 logger families). The corpus is fetched on demand into ./__corpus__/ by
// `npm run fetch-fixtures` (needs FIXTURES_TOKEN). When it isn't present — a public clone,
// a fork's CI without the secret — this whole suite skips, so the public build stays green.
//
// The contract lives in __corpus__/expected.json, generated by running THIS pipeline over
// the corpus and pairing it with each file's ground truth (device summary / second altimeter).
// Each fixture asserts one of: an auto-detected parser + numeric headline numbers within a
// tolerance of ground truth; a generic-mapper fallback with the right roles; or a deliberate
// rejection (Blue Raven high-rate files). Files Debrief currently mis-reads are recorded with
// a `knownIssue` and parsed-but-not-asserted, so the corpus documents the gap without locking
// a wrong number in as correct — fix the parser, then drop the knownIssue to turn on the assert.

const CORPUS = fileURLToPath(new URL('./__corpus__/', import.meta.url));
const SPEC = `${CORPUS}expected.json`;
// Committed contract overrides, versioned with the code rather than fetched with the
// corpus — see corpus-overrides.json. Merged over the fetched spec by file, so a parser
// fix and its updated expectation land together even though the corpus (and its
// expected.json) is a separately-released asset that lags the code.
const OVERRIDES = fileURLToPath(new URL('./corpus-overrides.json', import.meta.url));
const present = existsSync(SPEC);

const G0 = 9.80665;

type Assert = { metric: string; value: number; unit: string; tolPct: number };
interface Fixture {
  file: string;
  expect: { kind: 'flight' | 'mapping' | 'reject'; parser?: string; rejectMatch?: string };
  requireChannels?: string[];
  requireRoles?: string[];
  assert?: Assert[];
  knownIssue?: string;
  note?: string;
}

/** Convert one of Debrief's SI metrics into the unit the ground truth is stated in. */
function toStatedUnit(metric: string, si: number, unit: string): number {
  if (metric === 'maxAccel' && (unit === 'g' || unit === 'G')) return si / G0;
  const from = metric === 'apogee' ? 'm' : metric === 'maxAccel' ? 'm/s²' : 'm/s';
  return convert(si, from, unit);
}
const metricSI: Record<string, (m: ReturnType<typeof analyzeFlight>['metrics']) => number | null> = {
  apogee: (m) => m.apogeeAltitude,
  maxVelocity: (m) => m.maxVelocity,
  maxAccel: (m) => m.maxAcceleration,
  drogue: (m) => m.drogueDescentRate,
  main: (m) => m.mainDescentRate,
};

/**
 * Physical/logical invariants every real flight's analysis must satisfy, whatever
 * the logger — a standing guard against a metric that contradicts itself (the kind
 * of bug that a golden-value assert on one number can miss). Checked on every
 * non-anomalous corpus flight, so a regression anywhere in the pipeline trips here.
 */
function assertInvariants(a: ReturnType<typeof analyzeFlight>, name: string): void {
  const m = a.metrics;
  const apo = m.apogeeAltitude;
  const ctx = (msg: string) => `${name}: ${msg}`;

  // Deceleration is a deceleration — never a positive number dressed up as one.
  if (Number.isFinite(m.maxDeceleration)) expect(m.maxDeceleration, ctx('maxDeceleration ≤ 0')).toBeLessThanOrEqual(0);
  // Max acceleration and boost average are positive, and the average never exceeds the peak.
  if (m.avgBoostAcceleration != null) {
    expect(m.avgBoostAcceleration, ctx('avgBoost > 0')).toBeGreaterThan(0);
    if (Number.isFinite(m.maxAcceleration)) expect(m.avgBoostAcceleration, ctx('avgBoost ≤ max')).toBeLessThanOrEqual(m.maxAcceleration + 0.5);
  }
  // Thrust-to-weight off the pad, when read, is a sane launch number.
  if (m.liftoffTWR != null) {
    expect(m.liftoffTWR, ctx('TWR ≥ 1')).toBeGreaterThanOrEqual(1);
    expect(m.liftoffTWR, ctx('TWR < 100')).toBeLessThan(100);
  }
  // The design points all happen at or below apogee.
  // A withheld altitude (the record contradicted itself at that instant) is NaN, and is
  // not a value to bound — only a reported one is checked.
  if (Number.isFinite(m.maxVelocityAltitude)) expect(m.maxVelocityAltitude, ctx('maxVelAlt ≤ apogee')).toBeLessThanOrEqual(apo + 5);
  if (m.maxDynamicPressureAltitude != null) expect(m.maxDynamicPressureAltitude, ctx('maxQ alt ≤ apogee')).toBeLessThanOrEqual(apo + 5);
  if (m.transonicAltitude != null) expect(m.transonicAltitude, ctx('transonic alt ≤ apogee')).toBeLessThanOrEqual(apo + 5);
  if (m.burnoutAltitude != null) expect(m.burnoutAltitude, ctx('burnout alt ≤ apogee')).toBeLessThanOrEqual(apo + 5);
  // No reported ascent altitude may be higher than the flight's own measured speed can
  // account for: over the stretch from liftoff, the mean climb rate cannot exceed the
  // fastest the rocket was going in it. That is the mean value theorem, not a tolerance,
  // and the small allowance below is for barometric wander alone. Only where the speed is
  // measured — a barometric velocity comes from this very altitude trace, so the check
  // would be circular. Reading an axial speed as vertical makes the cap generous, which is
  // the safe direction.
  if (a.series.velocitySource === 'device') {
    const t = a.series.time;
    const h = a.series.altitude;
    const lift = a.events.find((e) => e.type === 'liftoff');
    const apoEv = a.events.find((e) => e.type === 'apogee');
    if (lift && apoEv && apoEv.index > lift.index) {
      const band = Math.max(30, apo * 0.03);
      let peak = 0;
      const ceilAt = new Float64Array(t.length);
      for (let i = lift.index; i <= apoEv.index; i++) {
        const v = a.series.velocity[i];
        if (Number.isFinite(v) && v > peak) peak = v;
        ceilAt[i] = (Number.isFinite(h[lift.index]) ? h[lift.index] : 0) + peak * (t[i] - t[lift.index]);
      }
      for (const e of a.events) {
        if (e.index <= lift.index || e.index > apoEv.index || !Number.isFinite(e.altitude)) continue;
        expect(
          e.altitude - ceilAt[e.index],
          ctx(
            `${e.type} altitude ${e.altitude.toFixed(0)} m exceeds what ${peak.toFixed(0)} m/s over ${(t[e.index] - t[lift.index]).toFixed(2)} s allows (${ceilAt[e.index].toFixed(0)} m)`,
          ),
        ).toBeLessThanOrEqual(band);
      }
    }
  }
  // A stated GPS apogee is a reading of the SAME flight. The two recordings are allowed
  // to disagree — that is the entire point of showing them side by side, and across the
  // corpus they differ by −2.7% to +6.5% — but an order-of-magnitude gap means what is
  // being reported is not this flight's apogee at all. Two corpus files are exactly that
  // (a 20-fix log and a 2.5-second telemetry capture, both reading essentially pad level
  // against a 3,000 ft flight); they are withheld, and this keeps them withheld.
  if (m.gpsApogeeAltitude != null && apo > 0) {
    expect(
      Math.abs(m.gpsApogeeAltitude - apo) / apo,
      ctx(`GPS apogee ${m.gpsApogeeAltitude.toFixed(0)} m vs barometric ${apo.toFixed(0)} m`),
    ).toBeLessThan(0.25);
    expect(m.gpsAscentFixes, ctx('a stated GPS apogee has fixes behind it')).toBeGreaterThan(0);
    // …and a GPS apogee that is close in height but nowhere near in time is a coincidence,
    // not a corroboration. Whichever it is, it must be judged rather than assumed: the
    // corpus holds one of each, and the second must not read as an agreement.
    const verdict = peakAgreement(
      { value: m.gpsApogeeAltitude, time: m.gpsApogeeTime },
      { value: apo, time: m.timeToApogee },
    );
    expect(
      ['agree', 'differ', 'different-peak'],
      ctx(`GPS peak verdict ${verdict}`),
    ).toContain(verdict);
    if (verdict !== 'different-peak' && m.gpsApogeeTime != null && Number.isFinite(m.timeToApogee)) {
      expect(
        Math.abs(m.gpsApogeeTime - m.timeToApogee),
        ctx('a corroborating GPS peak is at the same instant'),
      ).toBeLessThanOrEqual(peakTimeTolerance(m.timeToApogee));
    }
  }
  // A coast can't beat a vacuum. Coast efficiency is the height actually gained from
  // burnout to apogee over the v²/2g a body would gain with no drag at all, so a value above
  // 1 is a free lunch: it means the burnout velocity, the burnout altitude and the apogee
  // aren't from the same instant of the same flight. Measured across the corpus the highest
  // is 82%, so this has real headroom — it fires only on a pairing that has gone wrong.
  if (m.coastEfficiency != null) {
    expect(m.coastEfficiency, ctx(`coastEfficiency ${(m.coastEfficiency * 100).toFixed(0)}% ≤ 100%`)).toBeLessThanOrEqual(1);
    expect(m.coastEfficiency, ctx('coastEfficiency > 0')).toBeGreaterThan(0);
  }
  // Descent rates are downward (positive); the main is the slow chute.
  if (m.drogueDescentRate != null) expect(m.drogueDescentRate, ctx('drogue ≥ 0')).toBeGreaterThanOrEqual(0);
  if (m.mainDescentRate != null) expect(m.mainDescentRate, ctx('main ≥ 0')).toBeGreaterThanOrEqual(0);
  if (m.wholeDescentRate != null) expect(m.wholeDescentRate, ctx('whole descent ≥ 0')).toBeGreaterThanOrEqual(0);
  // A MAIN descent rate has to have come from a detected main deployment. Without one there
  // is no main leg to measure, and what gets reported is the whole apogee-to-landing average
  // wearing the label a flyer sizes a parachute against — 18 of the corpus's 25 descending
  // flights were doing exactly that, from 17.0 to 148.5 ft/s, against a 20–50 ft/s band for
  // the seven that genuinely resolved one. It also put that average in the same cross-check
  // row as other recordings' real main legs (a false 121.6% disagreement on one flight).
  if (m.mainDescentRate != null) {
    expect(
      a.events.some((e) => e.type === 'main'),
      ctx(`a main descent rate of ${m.mainDescentRate.toFixed(1)} m/s needs a detected main deployment`),
    ).toBe(true);
  }
  // A main leg and a whole-descent average are different quantities and never both apply: the
  // second exists precisely because no deployment was found to split the descent at. Holding
  // both would mean one of them is the other wearing a label it hasn't earned.
  expect(
    m.mainDescentRate != null && m.wholeDescentRate != null,
    ctx('a flight has a main leg OR a whole-descent average, never both'),
  ).toBe(false);
  expect(
    m.drogueDescentRate != null && m.wholeDescentRate != null,
    ctx('a drogue leg means the descent was split, so there is no whole-descent average'),
  ).toBe(false);
  if (m.drogueDescentRate != null && m.mainDescentRate != null) expect(m.mainDescentRate, ctx('main ≤ drogue')).toBeLessThanOrEqual(m.drogueDescentRate + 0.5);
  // …and neither can beat a vacuum. The rocket is at rest at apogee, so nothing after it
  // exceeds √(2·g·h) — no drag model, no mass, nothing to tune. "main ≤ drogue" alone cannot
  // see this: with no drogue leg to compare against, three real corpus files reported a main
  // descent of 16,495, 8,303 and 749 ft/s, every one of them a derived-signal artefact and
  // every one of them printed as a rate a flyer might size a chute against.
  if (Number.isFinite(apo) && apo > 0) {
    const freeFall = Math.sqrt(2 * G0 * apo);
    for (const [what, v] of [['drogue', m.drogueDescentRate], ['main', m.mainDescentRate], ['whole-descent', m.wholeDescentRate]] as const) {
      if (v != null) expect(v, ctx(`${what} ${v.toFixed(1)} m/s beats a vacuum fall from ${apo.toFixed(0)} m (${freeFall.toFixed(0)} m/s)`)).toBeLessThanOrEqual(freeFall);
    }
  }
  // The clock adds up: boost + coast = time to apogee; ascent + descent = flight.
  if (m.burnTime != null && m.coastTime != null && Number.isFinite(m.timeToApogee))
    expect(Math.abs(m.burnTime + m.coastTime - m.timeToApogee), ctx('burn + coast = timeToApogee')).toBeLessThanOrEqual(Math.max(0.5, m.timeToApogee * 0.1));
  if (m.descentTime != null && m.flightTime != null && Number.isFinite(m.timeToApogee))
    expect(Math.abs(m.timeToApogee + m.descentTime - m.flightTime), ctx('ascent + descent = flight')).toBeLessThanOrEqual(0.5);
  // Battery only sags under load — the minimum never exceeds the resting start.
  if (m.batteryStartV != null && m.batteryMinV != null) expect(m.batteryMinV, ctx('battMin ≤ battStart')).toBeLessThanOrEqual(m.batteryStartV + 0.05);
  // Events are in flight order and none sits above apogee.
  const order = ['liftoff', 'burnout', 'apogee', 'main', 'landing']
    .map((t) => a.events.find((e) => e.type === t))
    .filter(Boolean) as { time: number; altitude: number; type: string }[];
  for (let i = 1; i < order.length; i++) expect(order[i].time, ctx(`${order[i - 1].type} before ${order[i].type}`)).toBeGreaterThanOrEqual(order[i - 1].time - 1e-6);
  // A withheld altitude is NaN — the record contradicted itself at that instant — and
  // there is nothing to bound; only reported altitudes are checked.
  for (const e of order) {
    if (Number.isFinite(e.altitude)) expect(e.altitude, ctx(`${e.type} not above apogee`)).toBeLessThanOrEqual(apo + 1);
  }
}

function runFixture(fx: Fixture) {
  const name = fx.file.split('/').pop() as string;
  // Decode from the raw bytes exactly as the app does (a file's bytes → decodeBytes),
  // not as UTF-8 — otherwise a UTF-16 export (e.g. the RRC3 mDACS text file) would be
  // tested as mojibake the real drop-a-file path never sees. Keeps the corpus faithful
  // to production input.
  const text = decodeBytes(new Uint8Array(readFileSync(CORPUS + fx.file)));

  if (fx.expect.kind === 'reject') {
    // Debrief declines these on purpose (e.g. a Blue Raven high-rate file with no altitude)
    // with a helpful, user-facing message.
    expect(() => importFlight({ name, text })).toThrow(fx.expect.rejectMatch);
    return;
  }

  const res = importFlight({ name, text });
  expect(res.kind).toBe(fx.expect.kind);

  if (res.kind === 'mapping') {
    const t = res.table;
    const roles = t.columns.map((c) => c.role);
    for (const r of fx.requireRoles ?? []) expect(roles, `role ${r}`).toContain(r);
    // Exercise the full generic-mapper → build → analyze path on a real file. Mapping
    // fixtures were only role-checked, so a regression in analysing a mapped flight —
    // or in reconciling it against the device's own reported figures — was invisible.
    // Only when the auto-mapping found the essentials and the read isn't a known issue.
    const hasTime = roles.includes('time');
    const hasAltitude = roles.includes('altitude') || roles.includes('pressure');
    if (!fx.knownIssue && hasTime && hasAltitude) {
      const mappings = t.columns.filter((c) => c.role !== 'ignore').map((c) => ({ index: c.index, role: c.role, unit: c.unit }));
      const flight = buildFlight({
        source: name,
        format: 'generic',
        formatLabel: 'Generic CSV',
        headers: t.headers,
        dataRows: t.dataRows,
        mappings,
        reported: t.reported,
      });
      const a = analyzeFlight(flight);
      expect(Number.isFinite(a.metrics.apogeeAltitude), `${name} apogee finite`).toBe(true);
      expect(a.metrics.apogeeAltitude, `${name} apogee > 0`).toBeGreaterThan(0);
      assertInvariants(a, name);
      // A mapped flight can carry golden values like any other. The generic mapper is half
      // of the "universal" promise, and a file that only ever role-checked could drift its
      // numbers freely.
      assertGolden(fx, a);
      // Where the file states the device's own apogee, Debrief's independent read must
      // agree closely — a grounded guard that a real generic-CSV flight stays correct.
      for (const c of compareReported(flight.reported ?? [], a.metrics)) {
        if (c.reported.metric === 'apogeeAltitude' && c.hasComputed) {
          expect(c.deltaPct!, `${name} apogee ${convert(c.computed, 'm', 'ft').toFixed(0)}ft vs device ${convert(c.reported.value, 'm', 'ft').toFixed(0)}ft`).toBeLessThan(5);
        }
      }
    }
    return;
  }
  if (res.kind !== 'flight') return;

  if (fx.expect.parser) expect(res.parser.id).toBe(fx.expect.parser);
  for (const ch of fx.requireChannels ?? []) {
    expect(getChannel(res.flight, ch as ChannelKind), `channel ${ch}`).toBeTruthy();
  }

  // A documented mis-read or intentional anomaly: prove it still parses without throwing,
  // but don't assert the (known-wrong / meaningless) numbers or the invariants.
  if (fx.knownIssue) return;

  // Every real flight must satisfy the physical/logical invariants, whether or not
  // it carries golden-value asserts.
  const a = analyzeFlight(res.flight);
  assertInvariants(a, name);

  assertGolden(fx, a);
}

/**
 * The fixture's golden values against the analysis. Shared by both paths on purpose: a
 * mapping fixture's `assert` block used to be read and never checked — the mapping branch
 * returned before it — so a golden number written there looked armed and wasn't. Caught by
 * writing one, deliberately setting it wrong, and watching the suite stay green.
 */
function assertGolden(fx: Fixture, a: ReturnType<typeof analyzeFlight>): void {
  for (const as of fx.assert ?? []) {
    const si = metricSI[as.metric](a.metrics);
    expect(si, `${as.metric} present`).not.toBeNull();
    expect(Number.isNaN(si as number), `${as.metric} is NaN`).toBe(false);
    const got = toStatedUnit(as.metric, si as number, as.unit);
    const lo = as.value * (1 - as.tolPct / 100);
    const hi = as.value * (1 + as.tolPct / 100);
    expect(got, `${as.metric} ${got.toFixed(1)} ${as.unit} vs ${as.value}±${as.tolPct}%`).toBeGreaterThanOrEqual(lo);
    expect(got, `${as.metric} ${got.toFixed(1)} ${as.unit} vs ${as.value}±${as.tolPct}%`).toBeLessThanOrEqual(hi);
  }
}

describe('private corpus regression (lib/parsers/__corpus__)', () => {
  if (!present) {
    it.skip('corpus not fetched — run `npm run fetch-fixtures` (needs FIXTURES_TOKEN)', () => {});
    return;
  }
  const spec = JSON.parse(readFileSync(SPEC, 'utf8')) as { fixtures: Fixture[] };
  const byFile = new Map(spec.fixtures.map((f) => [f.file, f]));
  // Apply a committed override only when its target file is actually in the fetched
  // corpus — so an override for a not-yet-released (or renamed) file quietly no-ops
  // rather than trying to read a missing file.
  if (existsSync(OVERRIDES)) {
    const overrides = (JSON.parse(readFileSync(OVERRIDES, 'utf8')) as { fixtures: Fixture[] }).fixtures ?? [];
    for (const ov of overrides) if (existsSync(CORPUS + ov.file)) byFile.set(ov.file, ov);
  }
  for (const fx of byFile.values()) {
    it(`${fx.file}${fx.knownIssue ? ' [known issue: parse-only]' : ''}`, () => runFixture(fx));
  }
});

/** Load one corpus file to an analysed flight (named parser, else the generic mapper),
 *  or null if it isn't present or can't be read/mapped. */
function loadForCompare(file: string): CompareInput | null {
  const path = CORPUS + file;
  if (!existsSync(path)) return null;
  const text = decodeBytes(new Uint8Array(readFileSync(path)));
  const res = importFlight({ name: file.split('/').pop() as string, text });
  let flight;
  if (res.kind === 'flight') flight = res.flight;
  else if (res.kind === 'mapping') {
    const roles = res.table.columns.map((c) => c.role);
    if (!(roles.includes('time') && (roles.includes('altitude') || roles.includes('pressure')))) return null;
    const mappings = res.table.columns.filter((c) => c.role !== 'ignore').map((c) => ({ index: c.index, role: c.role, unit: c.unit }));
    flight = buildFlight({ source: file, format: 'generic', formatLabel: 'Generic CSV', headers: res.table.headers, dataRows: res.table.dataRows, mappings, reported: res.table.reported });
  } else return null;
  return { id: file, name: file, formatLabel: 'x', analysis: analyzeFlight(flight) };
}

// Independent recordings of ONE flight, same stage (redundant altimeters), that must
// agree closely — the reconciliation North Star under regression. This is what would
// have caught a baro second-derivative 'acceleration' reading ~300,000 m/s² next to its
// device partner's real ~180 m/s² peak: an apogee that agrees to a fraction of a percent
// beside an acceleration cross-check off by four orders of magnitude.
const RECON_GROUPS: {
  name: string;
  files: string[];
  apogeeTolPct: number;
  /** Optional: how far apart the recordings' time-to-apogee may fall (seconds). Only set
   *  where the group's liftoff detection genuinely agrees — a device that starts its log at
   *  a different moment shifts this without anything being wrong. */
  timeToApogeeTolS?: number;
}[] = [
  {
    name: 'iss-endurance: TeleMetrum + StratoLogger',
    apogeeTolPct: 3,
    files: [
      'altusmetrum/altusmetrum__issuiuc-endurance-20211030__TeleMetrum.csv',
      'perfectflite/perfectflite__issuiuc-endurance-20211030__StratoLogger.csv',
    ],
  },
  {
    name: 'iss-irec2023: EasyMega + TeleMega',
    apogeeTolPct: 3,
    files: [
      'altusmetrum/altusmetrum__issuiuc-irec2023-20230621__irec_2023_easymega.csv',
      'altusmetrum/altusmetrum__issuiuc-irec2023-20230621__irec_2023_telemega.csv',
    ],
  },
  {
    name: 'euroc-stacarl2: RRC3 + Eggtimer',
    apogeeTolPct: 4,
    files: [
      'missileworks-rrc3/missileworks-rrc3__euroc-stacarl2-europeanlocale__sta-carl2-rrc3.csv',
      'eggtimer/eggtimer__euroc-stacarl2-semicolon__sta-carl2-eggtimer.csv',
    ],
  },
  {
    // Four altimeters in one airframe on one flight — the tightest corroboration in the
    // corpus, and the case that would catch a regression the widest tolerance would miss.
    name: 'ac-lilnuke: four AltimeterCloud recordings',
    apogeeTolPct: 1,
    files: [
      'mercury-rocketry-altimetercloud/mercury__altimetercloud-lilnuke4alt-1784__1784.csv',
      'mercury-rocketry-altimetercloud/mercury__altimetercloud-lilnuke4alt-1785__1785.csv',
      'mercury-rocketry-altimetercloud/mercury__altimetercloud-lilnuke4alt-1786__1786.csv',
      'mercury-rocketry-altimetercloud/mercury__altimetercloud-lilnuke4alt-1796__1796.csv',
    ],
  },
  {
    // Different technologies on one flight: a Blue Raven's barometric altitude against a
    // Featherweight GPS's satellite altitude — they have no error in common.
    name: 'trf-f1-jan10: Blue Raven + Featherweight GPS',
    apogeeTolPct: 3,
    files: [
      'blueraven/blueraven__trf-f1machbuster-jan10__BLRVN87-bckup LR_01-10-2026_14_55_30.csv',
      'featherweight-gps/fwgps__trf-f1machbuster-jan10__GPSTrk05467_01-10-2026_14_55_35.csv',
    ],
  },
  {
    // An L3 cert flight recorded four ways — Blue Raven, GPS, and an Eggtimer Proton and
    // Quantum reformatted into the Featherweight layout.
    name: 'trf-lemiv-l3: Blue Raven + GPS + Proton + Quantum',
    apogeeTolPct: 4,
    // All four measure the same climb from their own liftoff, so time-to-apogee has to
    // agree too. It didn't: the Blue Raven's 50 Hz trace read 28.24 s against 23.6–23.9 s
    // because the plain highest sample landed on its drogue-deployment pressure transient,
    // nearly 4 s after the flight's own velocity had gone negative. Asserting the spread
    // keeps that from coming back.
    timeToApogeeTolS: 1.5,
    files: [
      'blueraven/blueraven__trf-lemiv-l3__BlRv_SN1537_LR_04-12-2025_12_45_49.csv',
      'featherweight-gps/fwgps__trf-lemiv-l3__GPSTrk05305_04-12-2025_12_45_50.csv',
      'generic-csv/genericcsv__trf-lemiv-l3__Proton-FW_format.csv',
      'generic-csv/genericcsv__trf-lemiv-l3__Quantum-FW_format.csv',
    ],
  },
];

describe('same-flight reconciliation (redundant recordings agree)', () => {
  if (!present) {
    it.skip('corpus not fetched — run `npm run fetch-fixtures` (needs FIXTURES_TOKEN)', () => {});
    return;
  }
  for (const g of RECON_GROUPS) {
    it(g.name, () => {
      const inputs = g.files.map(loadForCompare).filter((x): x is CompareInput => x != null);
      expect(inputs.length, `${g.name}: both recordings parse`).toBeGreaterThanOrEqual(2);
      const agree = crossCheck(buildComparison(inputs).flights);

      // Two recordings of one flight see the same apogee — corroboration, tight.
      const apo = agree.find((a) => a.key === 'apogee');
      expect(apo, `${g.name}: apogee cross-check present`).toBeTruthy();
      expect(apo!.spreadPct, `${g.name}: apogee spread ${apo!.spreadPct.toFixed(1)}%`).toBeLessThan(g.apogeeTolPct);

      // Where the recordings' liftoffs genuinely line up, the climb they timed has to
      // agree as well as the height it reached — the check that catches an apogee landing
      // on a deployment transient rather than on the peak.
      if (g.timeToApogeeTolS != null) {
        const tapo = agree.find((a) => a.key === 'timeToApogee');
        expect(tapo, `${g.name}: time-to-apogee cross-check present`).toBeTruthy();
        const spread = tapo!.max - tapo!.min;
        expect(spread, `${g.name}: time-to-apogee spread ${spread.toFixed(2)} s`).toBeLessThan(g.timeToApogeeTolS);
      }

      // No cross-check figure may be a physically impossible noise spike — the guard
      // that keeps a derived-signal artefact from ever being reported as agreement.
      const acc = agree.find((a) => a.key === 'maxAcceleration');
      if (acc) expect(acc.max / G0, `${g.name}: max acceleration ${(acc.max / G0).toFixed(0)} g is sane`).toBeLessThan(200);
      const vel = agree.find((a) => a.key === 'maxVelocity');
      if (vel) expect(vel.max, `${g.name}: max speed ${vel.max.toFixed(0)} m/s is sane`).toBeLessThan(4000);
    });
  }
});

// One file, one flight, written twice. Four corpus files trip the multi-flight detector, and
// what Debrief should SAY about them differs: two hold the same flight recorded twice (so
// "read the others by splitting the file" would hand the flyer the same flight again), and
// two do not. The discriminator is the apogee measured against the file's own pad baseline —
// on that datum the genuine pair agree to 0.21% and 0.00% while the Eggtimer's second
// segment, a baro artefact documented in the corpus ground truth, is 92% away.
const DOUBLE_RECORDINGS: { file: string; twice: boolean; why: string }[] = [
  {
    file: 'blueraven/blueraven__trf-f1machbuster-jan10__BLRVN87-bckup LR_01-10-2026_14_55_30.csv',
    twice: true,
    why: '10,245 ft then 10,267 ft on one datum — 0.21% apart; the device itself states 10,266 ft',
  },
  {
    file: 'blueraven/blueraven__trf-f1machbuster-jan18__BlRv_159F1cm LR_01-18-2026_10_48_41.csv',
    twice: true,
    why: '6,296 ft twice — 0.00% apart',
  },
  {
    file: 'eggtimer/eggtimer__reddit-seb-earlydeploy-anomaly__Eggtimer_Data.csv',
    twice: false,
    why: '4,661 ft then 8,969 ft — 92% apart, and the file has no quiet pad window to share a datum from',
  },
  {
    file: 'blueraven/blueraven__issuiuc-sg1.2-20231118__SG1.2-Sustainer-November-BlueRaven-Low.txt',
    twice: false,
    why: 'a 19 ft fragment whose apogee is withheld entirely',
  },
];

describe('a file that holds the same flight twice says so', () => {
  if (!present) {
    it.skip('corpus not fetched — run `npm run fetch-fixtures` (needs FIXTURES_TOKEN)', () => {});
    return;
  }
  for (const c of DOUBLE_RECORDINGS) {
    const short = c.file.split('/').pop() as string;
    it(`${short} — ${c.twice ? 'one flight written twice' : 'not a double recording'} (${c.why})`, () => {
      const loaded = loadForCompare(c.file);
      expect(loaded, `${short} is in the corpus and parses`).toBeTruthy();
      const w = loaded!.analysis.warnings;
      expect(w.some((x) => /holds the same flight written twice/.test(x)), `${short}: "written twice"`).toBe(c.twice);
      expect(w.some((x) => /holds more than one flight/.test(x)), `${short}: "more than one flight"`).toBe(!c.twice);
    });
  }
});

// A record that stops at rest, well above the pad, is not a landing. Four corpus records do
// exactly that — the altitude flattens and the file ends between 2.0% and 7.5% of the
// flight's own apogee up, one of them 307 m in the air. Whether that is a barometer's zero
// wandering over a long descent or the log simply stopping is not something the record
// settles, so no landing, flight time or descent time is read from them. (The two records
// that DO end at rest near the ground, 0.23% and 0.25% up, are read — see the jan10 pair.)
const ENDS_AT_REST_ABOVE_THE_PAD: { file: string; pct: string }[] = [
  { file: 'missileworks-rrc3/missileworks-rrc3__xprs2015__XPRS_2015_Flight_Data.txt', pct: '7.47% — 307 m up' },
  { file: 'perfectflite/perfectflite__issuiuc-intrepid3tf2-20230305__AL0 march launch data.pf2', pct: '5.45% — 270 m up' },
  { file: 'altusmetrum/altusmetrum__issuiuc-endurance-20211030__TeleMetrum.csv', pct: '3.29% — 94 m up' },
  { file: 'altusmetrum/altusmetrum__issuiuc-irec2023-20230621__irec_2023_telemega.csv', pct: '2.02% — 168 m up' },
];

// A log that did not start on the pad carries every height with the same offset, and the
// record's own resting end says how big it is. The PerfectFlite AL0 file is the one that can
// be checked: Debrief reads a 4,957 m apogee where the device's summary states 4,686 — a
// 271 m disagreement, on a record that comes to rest 270 m above where it began. Subtracting
// that gives 4,687 m, 0.9 m from the device's own figure.
//
// Debrief states the offset rather than applying it: a reading corrected until it agrees with
// the cross-check that was meant to test it is agreement dressed up, and only one corpus file
// carries a summary to check against at all.
describe('a log that did not start on the pad says how far out its heights are', () => {
  if (!present) {
    it.skip('corpus not fetched — run `npm run fetch-fixtures` (needs FIXTURES_TOKEN)', () => {});
    return;
  }
  const AL0 = 'perfectflite/perfectflite__issuiuc-intrepid3tf2-20230305__AL0 march launch data.pf2';
  it('names the offset, and the device summary confirms its size', () => {
    const loaded = loadForCompare(AL0);
    expect(loaded, 'AL0 is in the corpus and parses').toBeTruthy();
    const a = loaded!.analysis;

    const note = a.warnings.find((w) => /doesn't start on the pad, and it comes to rest/.test(w));
    expect(note, 'the offset is stated').toBeTruthy();
    expect(note, 'with the metres and the direction').toMatch(/\d+ m above where the record begins/);

    // The size it states is the size the device's own summary implies, which is the whole
    // reason this is a diagnosis and not a guess.
    const rows = compareReported(loaded!.analysis.metrics ? (loadReported(AL0) ?? []) : [], a.metrics);
    const apoRow = rows.find((r) => r.reported.metric === 'apogeeAltitude' && r.hasComputed);
    expect(apoRow, 'the device states an apogee').toBeTruthy();
    const gap = a.metrics.apogeeAltitude - apoRow!.reported.value;
    const h = a.series.altitude;
    let rest = Infinity;
    const apoEv = a.events.find((e) => e.type === 'apogee')!;
    for (let i = apoEv.index; i < h.length; i++) if (Number.isFinite(h[i]) && h[i] < rest) rest = h[i];
    // 271.3 m of disagreement against a 270.4 m resting height: the same number.
    expect(
      Math.abs(gap - rest),
      `apogee gap ${gap.toFixed(1)} m vs resting height ${rest.toFixed(1)} m`,
    ).toBeLessThan(2);
  });
});

/** The device's own summary block for a corpus file, or null. */
function loadReported(file: string) {
  const path = CORPUS + file;
  if (!existsSync(path)) return null;
  const text = decodeBytes(new Uint8Array(readFileSync(path)));
  const res = importFlight({ name: file.split('/').pop() as string, text });
  return res.kind === 'flight' ? (res.flight.reported ?? null) : null;
}

describe('a record that ends at rest above the pad is not a landing', () => {
  if (!present) {
    it.skip('corpus not fetched — run `npm run fetch-fixtures` (needs FIXTURES_TOKEN)', () => {});
    return;
  }
  for (const c of ENDS_AT_REST_ABOVE_THE_PAD) {
    const short = c.file.split('/').pop() as string;
    it(`${short} (${c.pct})`, () => {
      const loaded = loadForCompare(c.file);
      expect(loaded, `${short} is in the corpus and parses`).toBeTruthy();
      const m = loaded!.analysis.metrics;
      expect(m.descentTime, `${short}: no descent time`).toBeNull();
      expect(m.flightTime, `${short}: no flight time`).toBeNull();
      // …and the flyer is told why. A tile that is simply absent, among warnings about
      // baselines and sample rates that explain something else, is not an explanation.
      const why = loaded!.analysis.warnings.find((w) => /never reaches the ground/.test(w));
      expect(why, `${short}: says why the landing is withheld`).toBeTruthy();
      expect(why, `${short}: names the height it stopped at`).toMatch(/\d+ m above the pad/);
    });
  }
});

// …and the flight this all exists for. One Blue Raven file holds the jan10 flight twice: the
// copy that starts on the pad is cut 3.3 s after apogee, and the copy that runs to the ground
// starts in the trough with no pad of its own. Read on the file's shared datum, the second
// copy supplies the descent clock. The check that it is right is a different device: a
// Featherweight GPS recorded the same flight and lands within a second of it.
describe('the descent clock read from a file’s second copy', () => {
  if (!present) {
    it.skip('corpus not fetched — run `npm run fetch-fixtures` (needs FIXTURES_TOKEN)', () => {});
    return;
  }
  it('agrees with the separate GPS recording of the same flight', () => {
    const br = loadForCompare('blueraven/blueraven__trf-f1machbuster-jan10__BLRVN87-bckup LR_01-10-2026_14_55_30.csv');
    const gps = loadForCompare('featherweight-gps/fwgps__trf-f1machbuster-jan10__GPSTrk05467_01-10-2026_14_55_35.csv');
    expect(br, 'the Blue Raven is in the corpus').toBeTruthy();
    expect(gps, 'the Featherweight GPS is in the corpus').toBeTruthy();
    const b = br!.analysis.metrics;
    const g = gps!.analysis.metrics;

    // The clock came from the other copy, and says so.
    expect(b.descentSource).toBe('second-copy');
    expect(b.descentTime, 'a descent time is read').not.toBeNull();
    // The rates did not come across — an unresolved deployment would average this flight's
    // 50.7 m/s drogue and 6.2 m/s main into one figure labelled "main".
    expect(b.mainDescentRate, 'no descent rate is taken from the second copy').toBeNull();
    expect(b.drogueDescentRate).toBeNull();

    // Two devices, one flight: the descent they timed has to be the same descent.
    expect(g.descentTime, 'the GPS timed the descent too').not.toBeNull();
    expect(
      Math.abs(b.descentTime! - g.descentTime!),
      `descent time: Blue Raven ${b.descentTime!.toFixed(2)} s vs GPS ${g.descentTime!.toFixed(2)} s`,
    ).toBeLessThan(2);

    // The climb still comes from the copy that starts on the pad, so flight time adds up.
    expect(Math.abs(b.timeToApogee + b.descentTime! - b.flightTime!)).toBeLessThan(0.01);
  });
});

// A speed differentiated from an altitude never confirms a Mach-1 crossing — and the GPS
// carve-out that used to exist is what this pins down. The reasoning behind it was that
// nothing distorts a GPS through the transonic region the way a shock over a static port
// distorts a barometer. True, and beside the point: the error in a GPS speed comes from
// differentiating a coarse, lagging altitude. Both corpus GPS flights that a second
// instrument also recorded measure it, and both run HIGH — so the crossing is flagged.
describe('a GPS-derived speed does not confirm a supersonic flight', () => {
  if (!present) {
    it.skip('corpus not fetched — run `npm run fetch-fixtures` (needs FIXTURES_TOKEN)', () => {});
    return;
  }

  it('reads high against the instrument that measured the same flight (Mach 1.46 vs 1.14)', () => {
    const gps = loadForCompare('featherweight-gps/fwgps__trf-f1machbuster-jan18__GPS_GS03748_01-18-2026_10_32_45.csv');
    const br = loadForCompare('blueraven/blueraven__trf-f1machbuster-jan18__BlRv_159F1cm LR_01-18-2026_10_48_41.csv');
    expect(gps, 'the ground-station log is in the corpus').toBeTruthy();
    expect(br, 'the Blue Raven is in the corpus').toBeTruthy();
    const g = gps!.analysis.metrics;
    const b = br!.analysis.metrics;
    // The Blue Raven's speed is a measurement (its own velocity channel); the GPS one is
    // this altitude differentiated at about 1 Hz.
    expect(br!.analysis.series.velocitySource).toBe('device');
    expect(gps!.analysis.series.velocitySource).toBe('baro');
    expect(gps!.analysis.series.altitudeSource).toBe('gps');
    // The gap between them is the whole point: 31% on the speed, and it is one-directional.
    expect(g.maxVelocity! / b.maxVelocity!, 'the GPS peak runs high, not soft').toBeGreaterThan(1.2);
    // …and the flyer is told so, in the language of the sensor that produced it — the
    // barometric shock-over-the-port warning would name the wrong failure here.
    const why = gps!.analysis.warnings.find((w) => /worked out from the GPS altitude/.test(w));
    expect(why, 'the GPS peak says what it is').toBeTruthy();
    expect(why, 'and which way its error runs').toMatch(/runs the peak high/);
  });

  it('flags the crossing it does detect instead of asserting it', () => {
    const gps = loadForCompare('featherweight-gps/fwgps__trf-lemiv-l3__GPSTrk05305_04-12-2025_12_45_50.csv');
    expect(gps, 'the tracker log is in the corpus').toBeTruthy();
    const m = gps!.analysis.metrics;
    expect(m.transonicTime, 'this one does cross Mach 1 on the derived speed').not.toBeNull();
    expect(m.transonicUnconfirmed, 'and the crossing is not asserted').toBe(true);
  });

  it('still confirms a crossing the device itself measured', () => {
    const br = loadForCompare('blueraven/blueraven__trf-f1machbuster-jan18__BlRv_159F1cm LR_01-18-2026_10_48_41.csv');
    const m = br!.analysis.metrics;
    expect(m.transonicTime, 'the Blue Raven crossed Mach 1').not.toBeNull();
    expect(m.transonicUnconfirmed, 'a measured speed still settles it').toBe(false);
  });
});
